---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus
  name: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      nodeName: k3os-6802
      containers:
        - name: prometheus
          image: prom/prometheus
          args: 
            - "--storage.tsdb.retention.time=12h"
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
            - "--web.external-url"
            - "http://k3os-6802/prometheus"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
              name: http-prometheus
              protocol: TCP
          volumeMounts:
            - mountPath: /prometheus
              name: prometheus-pv
          volumeMounts:
            - mountPath: /etc/prometheus
              name: prometheus-config-pv
      volumes:
        - name: prometheus-pv
          persistentVolumeClaim:
            claimName: prometheus-pvc
        - name: prometheus-config-pv
          configMap:
            defaultMode: 420
            name: prometheus
            #persistentVolumeClaim:
            #claimName: prometheus-config-pvc
