---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prometheus
  name: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      nodeName: k3os-6802
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: prometheus
          image: prom/prometheus
          args: ["--config.file=/etc/prometheus/prometheus.yml", "--web.external-url", "http://k3os-6802:80/prometheus"]
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
              name: http-prometheus
              protocol: TCP
          volumeMounts:
            - mountPath: /prometheus
              name: prometheus-pv
          volumeMounts:
            - mountPath: /etc/prometheus
              name: prometheus-config-pv
      volumes:
        - name: prometheus-pv
          persistentVolumeClaim:
            claimName: prometheus-pvc
        - name: prometheus-config-pv
          persistentVolumeClaim:
            claimName: prometheus-config-pvc
