---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  selector:
    app.kubernetes.io/name: prometheus
  ports:
    - port: 9090
      name: http-prometheus
      protocol: TCP
      targetPort: http-prometheus
